require 'mechanize'
require 'pry'
require 'awesome_print'
require 'pg'
require_relative 'general_assembly.rb'
require_relative 'members_of_parliament.rb'
require_relative 'member_of_parliament.rb'
require_relative 'data_builder.rb'
require_relative 'db_settings.rb'

GA_LINK_IDENITFIER          = 'efn-tmra.html?thing='
MP_LINKS_IDENTIFIER         = 'dba-bin/raedur.pl?radsv=0&lthing'
SPEECH_LINK_IDENTIFIER      = '/altext/raeda/'
SPEECH_LINK_IDENTIFIER_OLD  = '/altext/gomulraeda.php4'
SPEECH_DIV_IDENTIFIER       = 'div#raeda_efni'
SPEECH_DIV_IDENTIFIER_OLD   = ''
